live_config_reload = true

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#06070c"
foreground = "#fffbf6"

[font]
size = 14.0

[font.bold]
family = "Sauce Code Pro NF"
style = "Bold"

[font.bold_italic]
family = "Sauce Code Pro NF"
style = "Bold Italic"

[font.italic]
family = "Sauce Code Pro NF"
style = "Italic"

[font.normal]
family = "Sauce Code Pro NF"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 5
