[general]
live_config_reload = true

import = [
    # This is a symlink to the current color. See alacritty-theme-switcher.sh
    # and the user systemd units for how it's managed.
    "~/.config/alacritty/active-theme.toml",
]

[font]
size = 14.0

[font.bold]
family = "Sauce Code Pro NF"
style = "Bold"

[font.bold_italic]
family = "Sauce Code Pro NF"
style = "Bold Italic"

[font.italic]
family = "Sauce Code Pro NF"
style = "Italic"

[font.normal]
family = "Sauce Code Pro NF"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.8

[window.padding]
x = 10
y = 5
