#!/bin/bash -e

source helpers.sh

git submodule init
git submodule update

install_dotfile ackrc
install_dotfile bashrc
install_dotfile vim
install_dotfile vimrc
install_dotfile tmux.conf
install_dotfile bin ~/bin
