#!/bin/bash -e

source helpers.sh

cat <<PACKAGES | xargs sudo apt-get install -y
vim-gnome
ttf-bitstream-vera
pyflakes

ttf-mscorefonts-installer

i3
gnome-settings-daemon
redshift-gtk
PACKAGES

###### gvim
install_dotfile gvimrc

###### GNOME+i3
# configs
install_xdg_config i3
install_xdg_config i3status

# use the xft-supporting version of dmenu
sudo update-alternatives --set dmenu /usr/bin/dmenu.xft

# add session option for GNOME+i3
cat <<GNOMESESSION | sudo tee /usr/share/gnome-session/sessions/gnome-i3.session > /dev/null
[GNOME Session]
Name=gnome-i3
RequiredComponents=gnome-settings-daemon;i3;
GNOMESESSION

cat <<XSESSION | sudo tee /usr/share/xsessions/gnome-i3.desktop > /dev/null
[Desktop Entry]
Name=GNOME with i3
Comment=improved dynamic tiling window manager
Exec=gnome-session --session=gnome-i3
Type=XSession
XSESSION

# disable the nautilus desktop window
gsettings set org.gnome.desktop.background show-desktop-icons false

# make gnome-keyring-daemon time out unlocked gpg keys
gsettings set org.gnome.crypto.cache gpg-cache-method "'idle'"
gsettings set org.gnome.crypto.cache gpg-cache-ttl 300
