#!/bin/bash -e

source helpers.sh

cat <<PACKAGES | xargs sudo apt-get install -y
vim-nox
ttf-bitstream-vera
pyflakes

ttf-mscorefonts-installer

redshift-gtk

pass
xdotool
PACKAGES

install_xdg_config terminator

gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Shift><Alt>Return'

gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "passmenu"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "${DOTFILE_ROOT}/bin/passmenu"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "<Shift><Alt>p"
