"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[git_metrics]
disabled = false

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[sudo]
disabled = false

[time]
disabled = false
