# keep these in sync with the manual install process
packages = [
  "apparmor",
  "audit",
  "base",
  "base-devel",
  "btrfs-progs",
  "ccid",
  "chezmoi",
  "fwupd",
  "git",
  "libfido2",
  "linux",
  "linux-firmware",
  "man-db",
  "man-pages",
  "networkmanager",
  "nftables",
  "paru-bin",  # should not be in installer
  "paru-bin-debug",  # should not be in installer
  "pinentry",
  "sbctl",  # should not be in installer
  "sudo",
  "ufw",
]
