packages = [
  "adobe-source-han-sans-otc-fonts",
  "adobe-source-han-serif-otc-fonts",
  "adobe-source-sans-fonts",
  "adobe-source-serif-fonts",
  "baobab",
  "gdm",
  "ghostty",
  "gnome-bluetooth",
  "gnome-calendar",
  "gnome-characters",
  "gnome-clocks",
  "gnome-color-manager",
  "gnome-control-center",
  "gnome-disk-utility",
  "gnome-font-viewer",
  "gnome-keyring",
  "gnome-menus",
  "gnome-session",
  "gnome-settings-daemon",
  "gnome-shell",
  "gnome-shell-extension-appindicator",
  "gnome-shell-extension-pop-shell-git",
  "gnome-shell-extensions",
  "gnome-shell-extension-simply-workspaces-git",
  "gnome-software",
  "gnome-system-monitor",
  "gnome-system-monitor",
  "gnome-text-editor",
  "gnome-tweaks",
  "gnome-weather",
  "grilo-plugins",
  "gvfs",
  "loupe",
  "nautilus",
  "noto-fonts",
  "noto-fonts-emoji",
  "pipewire-jack",
  "pipewire-libcamera",
  "pipewire-pulse",
  "showtime",
  "snapshot",
  "sushi",
  "tecla",
  "ttf-sourcecodepro-nerd",
  "wireplumber",
  "wmctrl",
  "xdg-desktop-portal-gnome",
  "xdg-user-dirs-gtk",
]

[systemd]
"bluetooth.service" = { enabled = true }
