#!/usr/bin/env bash

shopt -s nullglob globstar

password_files=( "${PASSWORD_STORE_DIR}"/**/*.gpg )
password_files=( "${password_files[@]#"${PASSWORD_STORE_DIR}"/}" )
password_files=( "${password_files[@]%.gpg}" )

password_file=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -p 'Password ')

if [[ -n "$password_file" ]]; then
    xdotool - <<<"type --clearmodifiers -- $(pass show "$password_file" | head -n 1)"
fi
